[package]

name = "typeable"
version = "0.0.8"
authors = ["Jonathan Reem <jonathan.reem@gmail.com>"]
description = "Exposes Typeable, for getting TypeIds at runtime."
repository = "https://github.com/reem/rust-typeable"
license = "MIT"

